# Generated by Django 5.1.4 on 2025-01-08 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_bookedsession_pendingsessionrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingsessionrequest',
            name='requester_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterModelTable(
            name='bookedsession',
            table='booked_sessions',
        ),
        migrations.AlterModelTable(
            name='invite',
            table='invite',
        ),
        migrations.AlterModelTable(
            name='membershipplan',
            table='membership_plan',
        ),
        migrations.AlterModelTable(
            name='operator',
            table='operators',
        ),
        migrations.AlterModelTable(
            name='pendingsessionrequest',
            table='pending_sessions',
        ),
        migrations.AlterModelTable(
            name='usermembership',
            table='user_membership',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='user_profile',
        ),
    ]
