# Generated by Django 5.1.4 on 2025-01-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_pendingsessionrequest_requester_phone_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Operator',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('public', 'Public'), ('member', 'Member'), ('operator', 'Operator'), ('admin', 'Admin')], default='public', max_length=10),
        ),
    ]
