# Generated by Django 5.1.4 on 2025-01-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_delete_operator_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedsession',
            name='booked_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
