# Generated by Django 5.1.4 on 2025-01-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_userprofile_stripe_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipplan',
            name='price',
        ),
        migrations.RemoveField(
            model_name='membershipplan',
            name='stripe_price_id',
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='stripe_product_id',
            field=models.CharField(default='prod_123', max_length=100),
        ),
    ]
