# Generated by Django 5.1.6 on 2025-03-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_usermembership_stripe_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='discount',
            field=models.BooleanField(default=False),
        ),
    ]
